data:
  image: busybox
  volumes:
    - /usr/local/bundle
web:
  build: .
  command: bundle exec rails s -p 3001 -b '0.0.0.0'
  volumes:
    - .:/app
  volumes_from:
    - data
  ports:
    - "3001:3001"
